services:
  postgres:
    image: postgres:16-alpine
    container_name: eventquest-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: eventquest
      POSTGRES_PASSWORD: eventquest
      POSTGRES_DB: eventquest
    volumes:
      - eventquest_postgres_data:/var/lib/postgresql/data

volumes:
  eventquest_postgres_data:
